name: Auto-Increment Minor Version & NPM Deploy

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Auto-Update Minor Version
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.name 'github action'
          git config --global user.email 'what@brettstoddard.com'

      - name: Patch npm version
        run: npm version patch -m "[RELEASE] %s"

      - name: Update repo
        run: git push

  publish:
    npm: Publish to NPMjs
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup .npmrc file to publish to npm
      - name: setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
