name: Test

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: "main"
        description: "The full branch name to test"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Test directory and node
        run: |
          node -v
          pwd

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run test

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: example-production-files
          path: ./example/react-tableau-embed-live-examples/dist
